### ISSUE TITLE
example request

### ISSUE THREAD

**Issue by ruxi** [nadavbra/pwas#2]
Hi @nadavbra

Is there an formatting example for the genotyping_spec.csv for plink-format?

So far my csv file looks like this:

```
name,format,bed_file_path,bim_file_path,fam_file_path
mydata,plink,file.bed,file.bim,file.fam
```

When I try to run ```list_all_variants``` it return an pandas error for the genotyping_manager

> IndexError: single positional indexer is out-of-bounds

Thanks

**Comment by ruxi** [comment]
@nadavbra

**Comment by nadavbra** [comment]
Hi,

Of course!

Here you can find examples for the UK Biobank (in our filesystem): ftp://ftp.cs.huji.ac.il/users/nadavb/ukbb_genotyping_specs/
These files were generated by [ukbb_parser](https://github.com/nadavbra/ukbb_parser).

If you write this file manually, make sure that all files are referenced by full path.

If you are still facing errors and need help, please copy-paste the full stack traces you receive. 

Good luck,
Nadav

**Comment by ruxi** [comment]
Thanks for the quick reply @nadavbra.

I found the issue: my famfile was tab delimited the script only recognizes spaces. 

Made a pull request so that it recognizes both: https://github.com/nadavbra/pwas/pull/3

**Comment by nadavbra** [comment]
Thank you @ruxi  for making the effort to debug it and fix the code.
I merged your pull request.
