### ISSUE TITLE
Format for covariate columns

### ISSUE THREAD

**Issue by loreseeker** [nadavbra/pwas#4]
Hello, 

I am trying to run PWAS, but not on UKB data and I am having trouble formatting the dataset file for the pwas_test_genes command, namely, getting the covariate columns input right. Is there perhaps an example of what is the expected input format for the samples + phenotypes + covariates file and how the columns should be passed to the program?

What is confusing me is that the argument entry for  --covariate-cols is listing COL_NAMEs in the metavar (which work as strings for sample and phenotype columns), but expecting integers as type:
`    parser.add_argument('--covariate-cols', dest = 'covariate_cols', metavar = '<COL_NAME1>,<COL_NAME2>,...', type = int, nargs = '+', default = [], \
            help = 'Columns (within the dataset CSV file) to be considered as covariates. See also --covariate-cols-json-file.')`

My starting test dataset CSV looked like this:
sid,pheno,age,sex
per0,1,70,1
per1,1,65,1

I tried running this (based on the metavar format with a comma):
pwas_test_genes --gene-effect-scores-dir test_gene_effects --dataset-file test_dataset.csv --per-gene-pwas-results-dir pwas_test --sample-id-col sid --phenotype-col pheno --covariate-cols age,sex
The command complained about non-integer values, so I tried renaming the covariate columns:
sid,pheno,1,2
per0,1,70,1
per1,1,65,1

And tried using  --covariate-cols 1 2, but the following error happened:

[2021_02_18-15:07:24] 2 covariates will be included.
[2021_02_18-15:07:24] Loaded the dataset (test_num_head.csv): 2000 samples x 3 columns.
Traceback (most recent call last):
  File "/usr/local/bin/pwas_test_genes", line 4, in <module>
    __import__('pkg_resources').run_script('pwas==1.0.4', 'pwas_test_genes')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/pwas-1.0.4-py3.6.egg/EGG-INFO/scripts/pwas_test_genes", line 138, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 5004, in dropna
    raise KeyError(list(np.compress(check, subset)))
KeyError: ['1', '2']

I also tried omitting the header (although the samples count indicates that the command expects one) and passing combinations of 1,2, [1,2], '[1,2]', '1 2', '1,2' on the off-chance that one of them will work, but no luck. Also tried 0 1, 1 2, 2 3, and 3 4 in case it wanted indices in some coordinate system.

An example input format for a CSV with covariates and the corresponding command line invocation for --covariate-cols would be really appreciated, assuming that's what's causing the issue. 

In case it helps, I'm running on Ubuntu, Python 3.6.9, pandas 1.1.5, numpy 1.19.5.

Thank you for your time.

**Comment by nadavbra** [comment]
Hi @loreseeker ,

I really apologize. This seems to be a bug. When testing PWAS, I always used --covariate-cols-json-file but never --covariate-cols.
Anyway, I fixed it (changed the type of --covariate-cols to str).

You can install the updated version by cloning the pwas repository (I haven't yet submitted it to pip), or you can use --covariate-cols-json-file instead (just create a JSON file listing the covariates and reference it using this argument). 

Let me know if this works for you know and whether you encounter more issues. 

Nadav

**Comment by loreseeker** [comment]
Hi @nadavbra,

thank you for the reply and the fix to the code. For now, I created the JSON file instead, like you suggested:
{
	"age": "age",
	"sex": "sex"
}
and the analysis seems to be working. Thank you again!

**Comment by nadavbra** [comment]
Glad it worked out for now :)

Just for future reference - it is simpler (and more appropriate) to use a JSON list instead of a dictionary, i.e.: 
["age","sex"]

**Comment by loreseeker** [comment]
Thank you, that's a good point. :) I'll change the format.
