### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by lauragreco** [nadavbra/pwas#6]
This issue was resolved uninstalling and re-installing packages

**Comment by nadavbra** [comment]
@lauragreco Which version of Python are you using?
Were you able to run it on the example dataset provided in the repo?

**Comment by nadavbra** [comment]
@lauragreco Which version of Python are you using?
Were you able to run it on the example dataset provided in the repo?

**Comment by nadavbra** [comment]
@lauragreco Were you able to run it on the example dataset provided in the repo?

**Comment by nadavbra** [comment]
Are you running it from command line or some Python console?
